import type { GraphItem } from "./types";

/* Content crawled from oradevelopers.com (see scripts/crawl.mjs) and
   shaped like flattened Optimizely Graph results. Copy is condensed from
   the live pages; urls point at the live site; images are local copies
   of live assets. A few venue and career items are drafted for the POC
   to exercise facets and personalisation. */

const LIVE = "https://oradevelopers.com";

export const items: GraphItem[] = [
  /* Egypt communities */
  {
    id: "zed-sheikh-zayed",
    title: "ZED El Sheikh Zayed",
    titleAr: "زيد الشيخ زايد",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "165 feddan of luxurious real estate in West Cairo surrounding the one of a kind ZED Park, minutes from the 26th of July Corridor and Alex Desert Road.",
    snippetAr:
      "165 فدانا من العقارات الفاخرة في غرب القاهرة تحيط بحديقة زيد الفريدة، على دقائق من محور 26 يوليو وطريق إسكندرية الصحراوي.",
    url: `${LIVE}/properties/zed-elsheikh-zayed`,
    image: "/images/zed-elsheikh-zayed.jpg",
    boost: 8,
    relevance: 0.94,
    tags: ["family", "park", "apartments", "west cairo", "sheikh zayed", "mixed use", "community", "walkable"],
    palette: ["#c9a97c", "#8a6438"],
    segmentBoost: { resident: 2, firstTime: 2 },
    segmentNote: {
      resident: "Residents reach ZED Park, the sports facilities and the retail strip on foot.",
      firstTime: "Apartment releases include extended payment plans for first homes.",
    },
  },
  {
    id: "zed-east",
    title: "ZED East",
    titleAr: "زيد إيست",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "360 feddans of prime land in New Cairo with over 50 percent greenery: a residential led community of villas and apartments where every unit overlooks landscaped gardens, courtyards or The Club.",
    snippetAr:
      "360 فدانا من الأراضي المميزة في القاهرة الجديدة بمساحات خضراء تتجاوز 50 في المئة: مجتمع سكني من الفلل والشقق تطل كل وحداته على حدائق أو أفنية أو النادي.",
    url: `${LIVE}/properties/zed-east`,
    image: "/images/zed-east.jpg",
    boost: 8,
    relevance: 0.92,
    tags: ["family", "schools", "education", "villas", "apartments", "new cairo", "children", "park", "greenery"],
    palette: ["#b9a06e", "#7c5c33"],
    segmentBoost: { firstTime: 3, resident: 2 },
    segmentNote: {
      firstTime: "Apartment phases release with long payment plans for first buyers.",
      resident: "The Club, academies and clinics sit at the heart of the masterplan.",
    },
  },
  {
    id: "silversands-north-coast",
    title: "Silversands North Coast",
    titleAr: "سيلفرساندز الساحل الشمالي",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "Over 1 kilometre of sparkling beachfront on Egypt's North Coast: crystal white sands, swaying palms and a serene take on the Mediterranean at Ras El Hekma.",
    snippetAr:
      "أكثر من كيلومتر من الواجهة البحرية على الساحل الشمالي: رمال بيضاء ونخيل وإطلالة هادئة على المتوسط في رأس الحكمة.",
    url: `${LIVE}/properties/silversands-north-coast`,
    image: "/images/silversands-north-coast.jpg",
    boost: 9,
    relevance: 0.95,
    tags: ["sea", "seafront", "beach", "coastal", "apartments", "villas", "mediterranean", "sahel", "waterfront", "north coast"],
    palette: ["#9fc0bb", "#54837c"],
    segmentBoost: { investor: 2, firstTime: 1 },
    segmentNote: {
      investor: "Managed seasonal lettings support strong gross yields on the coast.",
      firstTime: "Chalet plans open the beachfront at accessible entry points.",
    },
  },
  {
    id: "solana",
    title: "Solana",
    titleAr: "سولانا",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "The boldest feat in New Zayed and beyond: a multitude of premium villa typologies made for multidimensional people, life in contrast on the bright side of West Cairo.",
    snippetAr:
      "أجرأ مشروع في زايد الجديدة وما بعدها: باقة من الفلل الفاخرة لمن يعيشون الحياة بأبعادها، حياة من التباين في الجانب المشرق من غرب القاهرة.",
    url: `${LIVE}/properties/solana-by-ora`,
    image: "/images/solana.jpg",
    boost: 7,
    relevance: 0.88,
    tags: ["villas", "garden", "family", "west cairo", "new zayed", "pools"],
    palette: ["#d3b184", "#96703f"],
    segmentBoost: { firstTime: 2 },
    segmentNote: {
      firstTime: "Twin villas open the collection below standalone pricing.",
    },
  },
  {
    id: "pyramid-hills",
    title: "Pyramid Hills",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "Facing the Great Pyramids of Giza, one of Egypt's most distinctive addresses: a perfect stage for tranquil living with a 360 degree view of Cairo.",
    url: `${LIVE}/properties/pyramid-hills`,
    image: "/images/pyramid-hills.jpg",
    boost: 6,
    relevance: 0.84,
    tags: ["villas", "giza", "views", "heritage", "pyramids", "museum"],
    palette: ["#c2a06a", "#7f5f34"],
    segmentBoost: { investor: 1 },
  },
  {
    id: "zed-towers",
    title: "ZED Towers",
    type: "Community",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "High rise living above ZED Park in Sheikh Zayed, with serviced apartments and skyline terraces over the largest green space in the area.",
    url: `${LIVE}/properties/zed-elsheikh-zayed`,
    image: "/images/zed-towers.jpg",
    boost: 7,
    relevance: 0.86,
    tags: ["apartments", "towers", "serviced", "skyline", "park"],
    palette: ["#b3a284", "#6e5d40"],
    segmentBoost: { investor: 3 },
    segmentNote: {
      investor: "Serviced units carry a managed rental programme.",
    },
  },

  /* Egypt venues */
  {
    id: "zed-park",
    title: "ZED Park",
    titleAr: "حديقة زيد",
    type: "Venue",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Hospitality",
    languages: ["en", "ar"],
    snippet:
      "The largest green space in Sheikh Zayed, accommodating sustainable, creative and active lifestyles at the heart of the ZED masterplan.",
    snippetAr:
      "أكبر مساحة خضراء في الشيخ زايد، تحتضن أنماط حياة مستدامة ومبدعة ونشطة في قلب مخطط زيد.",
    url: `${LIVE}/properties/zed-elsheikh-zayed`,
    image: "/images/zed-park.jpg",
    boost: 6,
    relevance: 0.85,
    tags: ["park", "family", "children", "outdoors", "events", "green"],
    palette: ["#a9bf94", "#5f7c4a"],
    segmentBoost: { resident: 3 },
  },
  {
    id: "zed-strip",
    title: "The Strip at ZED",
    type: "Venue",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Retail",
    languages: ["en"],
    snippet:
      "An open air retail promenade of cafes, dining and neighbourhood services running along ZED Park in Sheikh Zayed.",
    url: `${LIVE}/properties/zed-elsheikh-zayed`,
    image: "/images/zed-strip.jpg",
    boost: 5,
    relevance: 0.78,
    tags: ["retail", "dining", "cafes", "shopping", "promenade"],
    palette: ["#cbb18a", "#8d6f45"],
    segmentBoost: { resident: 2 },
  },
  {
    id: "silversands-beach-club",
    title: "Silversands Beach Club",
    type: "Venue",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "Cabanas, dining and summer residencies on the crystal white sands of Ras El Hekma, anchoring the Silversands shoreline.",
    url: `${LIVE}/properties/silversands-north-coast`,
    image: "/images/silversands-beach-club.jpg",
    boost: 5,
    relevance: 0.8,
    tags: ["beach", "sea", "club", "dining", "summer", "coastal"],
    palette: ["#93bdb6", "#4c7a72"],
  },
  {
    id: "zed-sports-club",
    title: "The Club, ZED East",
    type: "Venue",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "High grade sporting and hospitality facilities in landscaped gardens: a sports university, football and tennis academies and extensive pools.",
    url: `${LIVE}/properties/zed-east`,
    image: "/images/zed-sports.jpg",
    boost: 4,
    relevance: 0.74,
    tags: ["sports", "academies", "fitness", "pools", "family", "club"],
    palette: ["#a5b58e", "#5c714a"],
    segmentBoost: { resident: 2 },
  },
  {
    id: "zed-academy",
    title: "ZED East education district",
    titleAr: "الحي التعليمي في زيد إيست",
    type: "Venue",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Education",
    languages: ["en", "ar"],
    snippet:
      "Schools, academies and clinics clustered at the core of ZED East, planned so families reach daily education on foot.",
    snippetAr:
      "مدارس وأكاديميات وعيادات تتجمع في قلب زيد إيست، خطط لها بحيث تصل العائلات إلى التعليم اليومي سيرا على الأقدام.",
    url: `${LIVE}/properties/zed-east`,
    image: "/images/zed-academy.jpg",
    boost: 6,
    relevance: 0.82,
    tags: ["school", "schools", "education", "international", "children", "family", "academies"],
    palette: ["#b8a98a", "#6f5f3f"],
    segmentBoost: { resident: 2, firstTime: 2 },
  },

  /* UAE */
  {
    id: "bayn",
    title: "BAYN by ORA",
    titleAr: "بين من أورا",
    type: "Community",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "The city of the future at Ghantoot, 4.8 million square metres between Dubai and Abu Dhabi where city energy meets coastal serenity, without compromise.",
    snippetAr:
      "مدينة المستقبل في غنتوت، 4.8 مليون متر مربع بين دبي وأبوظبي حيث تلتقي طاقة المدينة بسكينة الساحل، دون أي تنازل.",
    url: `${LIVE}/properties/bayn-by-ora`,
    image: "/images/bayn.jpg",
    boost: 9,
    relevance: 0.93,
    tags: ["sea", "beachfront", "villas", "dubai", "abu dhabi", "ghantoot", "coastal", "waterfront", "city"],
    palette: ["#d5b586", "#9a7444"],
    segmentBoost: { investor: 2 },
    segmentNote: {
      investor: "Launch phases price below comparable Dubai waterfront stock.",
    },
  },
  {
    id: "bayn-shorefront",
    title: "BAYN Shorefront Villas",
    type: "Community",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "First row villas along BAYN's natural shoreline with private beach access and uninterrupted Gulf views.",
    url: `${LIVE}/properties/bayn-by-ora`,
    image: "/images/bayn-shore.jpg",
    boost: 7,
    relevance: 0.87,
    tags: ["beach", "sea", "villas", "private", "gulf", "waterfront"],
    palette: ["#c8ad7e", "#8a6a3c"],
    segmentBoost: { investor: 2 },
  },
  {
    id: "bayn-wellness",
    title: "BAYN Wellness Club",
    type: "Venue",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "A shoreline wellness house within BAYN's masterplan, balancing vibrancy and tranquility on the Ghantoot coast.",
    url: `${LIVE}/properties/bayn-by-ora`,
    image: "/images/bayn-wellness.jpg",
    boost: 4,
    relevance: 0.72,
    tags: ["wellness", "spa", "fitness", "health", "club"],
    palette: ["#cbb694", "#87714a"],
  },

  /* Cyprus */
  {
    id: "ayia-napa-marina",
    title: "Ayia Napa Marina",
    titleAr: "مارينا أيا نابا",
    type: "Community",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en", "ar"],
    snippet:
      "World class yachting facilities, retail boutiques, waterfront fine dining and nightlife on Cyprus's crystal clear seas: the ultimate Mediterranean lifestyle.",
    snippetAr:
      "مرافق يخوت عالمية ومتاجر ومطاعم راقية على الواجهة البحرية في مياه قبرص الصافية: نمط الحياة المتوسطي في أبهى صوره.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/ayia-napa-marina.jpg",
    boost: 8,
    relevance: 0.91,
    tags: ["marina", "sea", "yachts", "mediterranean", "apartments", "towers", "waterfront", "dining"],
    palette: ["#93b3c4", "#476f85"],
    segmentBoost: { investor: 2 },
    segmentNote: {
      investor: "Completed, income producing asset with an active resale market.",
    },
  },
  {
    id: "anm-east-tower",
    title: "Marina Residences, East Tower",
    type: "Community",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en"],
    snippet:
      "Sea view apartments in the twin towers above Ayia Napa Marina, delivered with berthing privileges and resort services.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/anm-towers.jpg",
    boost: 6,
    relevance: 0.84,
    tags: ["apartments", "sea", "views", "furnished", "marina", "tower"],
    palette: ["#88a9bb", "#3f6579"],
    segmentBoost: { investor: 3 },
    segmentNote: {
      investor: "Furnished stock lets year round through the marina rental desk.",
    },
  },
  {
    id: "anm-yacht-club",
    title: "Ayia Napa Marina Yacht Club",
    type: "Venue",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en"],
    snippet:
      "Members clubhouse, crew services and concierge berthing for 600 vessels at the heart of the marina.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/anm-yacht-club.jpg",
    boost: 4,
    relevance: 0.73,
    tags: ["yachts", "club", "berthing", "sailing", "members"],
    palette: ["#7fa3b6", "#3a5f73"],
  },
  {
    id: "anm-events-quarter",
    title: "The Events Quarter, Ayia Napa Marina",
    type: "Venue",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "An open air waterfront promenade hosting regattas, markets and summer concerts through the season.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/anm-events.jpg",
    boost: 3,
    relevance: 0.68,
    tags: ["events", "concerts", "waterfront", "promenade", "summer"],
    palette: ["#8fb0bf", "#48707f"],
  },

  /* Grenada and the Caribbean */
  {
    id: "silversands-villas-grenada",
    title: "Silversands Villas, Grenada",
    type: "Community",
    opco: "ORA Grenada",
    market: "Grenada",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "Private beachfront villas beside Silversands Grand Anse with grand living areas framed by 1,300 square feet of private pool reflecting the sea and sky.",
    url: `${LIVE}/properties/silversands-villas`,
    image: "/images/silversands-villas.jpg",
    boost: 7,
    relevance: 0.88,
    tags: ["beach", "sea", "villas", "caribbean", "resort", "managed", "waterfront", "pool"],
    palette: ["#a2c1a6", "#567f5f"],
    segmentBoost: { investor: 3 },
    segmentNote: {
      investor: "Qualifies for Grenada citizenship by investment at the approved threshold.",
    },
  },
  {
    id: "silversands-grand-anse",
    title: "Silversands Grand Anse",
    type: "Venue",
    opco: "ORA Hospitality",
    market: "Grenada",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "A contemporary luxury resort on Grand Anse beach: hotel, exclusive residences and nine awe inspiring villas dotted along the beach and hillside.",
    url: `${LIVE}/hospitality/silversands-grand-anse`,
    image: "/images/silversands-grand-anse.jpg",
    boost: 6,
    relevance: 0.85,
    tags: ["resort", "beach", "hotel", "pool", "caribbean", "suites"],
    palette: ["#98bba2", "#4e7758"],
  },
  {
    id: "silversands-beach-house",
    title: "Silversands Beach House",
    type: "Venue",
    opco: "ORA Hospitality",
    market: "Grenada",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "Just 30 rooms on Portici Beach, each under a distinct architectural canopy: an exclusive guest experience nestled in nature.",
    url: `${LIVE}/hospitality/silversands-beach-house`,
    image: "/images/silversands-beach-house.jpg",
    boost: 5,
    relevance: 0.79,
    tags: ["beach", "hotel", "spa", "boutique", "caribbean"],
    palette: ["#a6c3ab", "#5a8161"],
  },
  {
    id: "merveilles",
    title: "Merveilles, Port Louis",
    type: "Venue",
    opco: "ORA Hospitality",
    market: "Grenada",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "Grenada's premier entertainment hub in the heart of Port Louis: an ode to community, discovery and the beauty of being present, five miles from the airport.",
    url: `${LIVE}/hospitality/merveilles`,
    image: "/images/merveilles.jpg",
    boost: 4,
    relevance: 0.74,
    tags: ["entertainment", "dining", "marina", "caribbean", "promenade"],
    palette: ["#9dbfae", "#4f7a63"],
  },
  {
    id: "grenada-cbi-guide",
    title: "Investing in Grenada: citizenship by investment",
    type: "Page",
    opco: "ORA Grenada",
    market: "Grenada",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "How qualifying investments in Silversands real estate support an application for Grenadian citizenship.",
    url: `${LIVE}/properties/silversands-villas`,
    boost: 5,
    relevance: 0.77,
    tags: ["investment", "citizenship", "cbi", "passport", "guide", "yield"],
    palette: ["#b8c9b0", "#647f5c"],
    segmentBoost: { investor: 3 },
  },

  /* Greece */
  {
    id: "yi-mykonos",
    title: "Yi Hotel Mykonos",
    type: "Venue",
    opco: "ORA Hospitality",
    market: "Greece",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "A luxurious modern home experience rooted in Cycladic influences: whitewashed houses, meandering lanes and magnificent vistas of the Aegean.",
    url: `${LIVE}/hospitality/mykonos`,
    image: "/images/mykonos.jpg",
    boost: 4,
    relevance: 0.75,
    tags: ["hotel", "sea", "island", "aegean", "resort", "boutique"],
    palette: ["#a8bfd0", "#4d6b85"],
  },

  /* Pakistan */
  {
    id: "eighteen",
    title: "Eighteen, Islamabad",
    type: "Community",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "A secure and relaxing community of luxurious villas and apartments southwest of Islamabad, serviced by world class amenities around an 18 hole course.",
    url: `${LIVE}/properties/eighteen`,
    image: "/images/eighteen.jpg",
    boost: 7,
    relevance: 0.89,
    tags: ["golf", "villas", "apartments", "islamabad", "club", "family", "secure"],
    palette: ["#b5a887", "#6b5d3e"],
    segmentBoost: { resident: 1, firstTime: 1 },
  },
  {
    id: "eighteen-club",
    title: "The Club at Eighteen",
    type: "Venue",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "An 18 hole championship course, racquet centre and members clubhouse at the heart of Eighteen, now open for member play.",
    url: `${LIVE}/latest-news/eighteen-celebrates-the-opening-of-the-club`,
    image: "/images/eighteen-club.jpg",
    boost: 4,
    relevance: 0.75,
    tags: ["golf", "club", "sports", "members", "course"],
    palette: ["#a8ad86", "#5d6440"],
  },
  {
    id: "eighteen-golf-villas",
    title: "Eighteen Golf Villas",
    type: "Community",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Residential",
    languages: ["en"],
    snippet:
      "Fairway facing villas from half a kanal to two kanals, released in limited phases as handovers continue.",
    url: `${LIVE}/properties/eighteen`,
    image: "/images/eighteen-villas.jpg",
    boost: 5,
    relevance: 0.8,
    tags: ["golf", "villas", "fairway", "islamabad"],
    palette: ["#aeb28c", "#626947"],
    segmentBoost: { investor: 1 },
  },

  /* Iraq */
  {
    id: "madinat-al-ward",
    title: "Madinat Al Ward, Baghdad",
    titleAr: "مدينة الورد، بغداد",
    type: "Community",
    opco: "ORA Iraq",
    market: "Iraq",
    vertical: "Residential",
    languages: ["en", "ar"],
    snippet:
      "Baghdad's largest ever city: 61 million square metres, 25 kilometres southeast of the capital, delivering 120,000 new residential units around a grand central park.",
    snippetAr:
      "أكبر مدينة في تاريخ بغداد: 61 مليون متر مربع على بعد 25 كيلومترا جنوب شرق العاصمة، تضم 120 ألف وحدة سكنية حول حديقة مركزية كبرى.",
    url: `${LIVE}/properties/madinat-al-ward`,
    image: "/images/madinat-al-ward.jpg",
    boost: 7,
    relevance: 0.86,
    tags: ["baghdad", "city", "apartments", "villas", "park", "masterplan", "iraq"],
    palette: ["#c4a37a", "#7d5f3b"],
    segmentBoost: { investor: 1, firstTime: 2 },
    segmentNote: {
      firstTime: "Designed to widen access to quality first homes at national scale.",
    },
  },
  {
    id: "maw-grand-park",
    title: "The Grand Park, Madinat Al Ward",
    type: "Venue",
    opco: "ORA Iraq",
    market: "Iraq",
    vertical: "Hospitality",
    languages: ["en"],
    snippet:
      "Parkfront residences and public green space at the centre of Madinat Al Ward's masterplan.",
    url: `${LIVE}/properties/madinat-al-ward`,
    image: "/images/maw-park.jpg",
    boost: 3,
    relevance: 0.66,
    tags: ["park", "green", "public", "baghdad"],
    palette: ["#a9bd93", "#5d744a"],
  },

  /* Market landing pages */
  {
    id: "market-egypt",
    title: "ORA in Egypt",
    titleAr: "أورا في مصر",
    type: "Market",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Corporate",
    languages: ["en", "ar"],
    snippet:
      "Five live destinations across Cairo and the North Coast: ZED El Sheikh Zayed, ZED East, Silversands, Solana and Pyramid Hills.",
    snippetAr:
      "خمس وجهات قائمة في القاهرة والساحل الشمالي: زيد الشيخ زايد وزيد إيست وسيلفرساندز وسولانا وبيراميد هيلز.",
    url: `${LIVE}/properties`,
    image: "/images/zed-elsheikh-zayed.jpg",
    boost: 6,
    relevance: 0.82,
    tags: ["egypt", "cairo", "north coast", "portfolio", "destinations"],
    palette: ["#c7a877", "#84613a"],
  },
  {
    id: "market-uae",
    title: "ORA in the UAE",
    titleAr: "أورا في الإمارات",
    type: "Market",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Corporate",
    languages: ["en", "ar"],
    snippet:
      "A new chapter on the Ghantoot shoreline: BAYN, the city of the future between two capitals.",
    snippetAr:
      "فصل جديد على شاطئ غنتوت: بين، مدينة المستقبل بين عاصمتين.",
    url: `${LIVE}/properties/bayn-by-ora`,
    image: "/images/bayn.jpg",
    boost: 6,
    relevance: 0.8,
    tags: ["uae", "dubai", "abu dhabi", "ghantoot", "portfolio"],
    palette: ["#d2b489", "#93703f"],
  },
  {
    id: "market-cyprus",
    title: "ORA in Cyprus",
    type: "Market",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "The eastern Mediterranean flagship: a completed marina destination in Ayia Napa.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/anm-hero.jpg",
    boost: 5,
    relevance: 0.76,
    tags: ["cyprus", "mediterranean", "marina", "portfolio"],
    palette: ["#8fb0c2", "#44697e"],
  },
  {
    id: "market-grenada",
    title: "ORA in Grenada",
    type: "Market",
    opco: "ORA Grenada",
    market: "Grenada",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "Resort living and hospitality on two of the Caribbean's most protected beaches.",
    url: `${LIVE}/hospitality`,
    image: "/images/silversands-grand-anse.jpg",
    boost: 5,
    relevance: 0.74,
    tags: ["grenada", "caribbean", "resort", "portfolio"],
    palette: ["#9fbfa4", "#54795c"],
  },
  {
    id: "market-pakistan",
    title: "ORA in Pakistan",
    type: "Market",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "Eighteen brings resort standard living and a championship course to the capital region.",
    url: `${LIVE}/properties/eighteen`,
    image: "/images/eighteen-hero.jpg",
    boost: 5,
    relevance: 0.73,
    tags: ["pakistan", "islamabad", "portfolio"],
    palette: ["#b2a683", "#67593a"],
  },
  {
    id: "market-iraq",
    title: "ORA in Iraq",
    titleAr: "أورا في العراق",
    type: "Market",
    opco: "ORA Iraq",
    market: "Iraq",
    vertical: "Corporate",
    languages: ["en", "ar"],
    snippet:
      "A historic milestone for Baghdad: Madinat Al Ward, the largest city development in the country's history.",
    snippetAr:
      "إنجاز تاريخي لبغداد: مدينة الورد، أكبر مشروع مدينة في تاريخ البلاد.",
    url: `${LIVE}/properties/madinat-al-ward`,
    image: "/images/maw-park.jpg",
    boost: 5,
    relevance: 0.72,
    tags: ["iraq", "baghdad", "portfolio"],
    palette: ["#c0a075", "#7a5c36"],
  },

  /* Group pages */
  {
    id: "about-odhl",
    title: "About ORA Developers",
    titleAr: "عن أورا للتطوير",
    type: "Page",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en", "ar"],
    snippet:
      "Founded by Naguib Sawiris, ORA creates living, breathing lifestyle destinations across three continents with a real sense of community spirit.",
    snippetAr:
      "أسسها نجيب ساويرس، وتبني أورا وجهات نابضة بالحياة في ثلاث قارات بروح مجتمعية حقيقية.",
    url: `${LIVE}/about`,
    image: "/images/about.jpg",
    boost: 5,
    relevance: 0.7,
    tags: ["about", "group", "sawiris", "company", "vision"],
    palette: ["#26211b", "#4a443c"],
  },
  {
    id: "reimagining-time",
    title: "Reimagining Time",
    type: "Page",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "The philosophy behind every ORA destination: meticulously crafted moments that combine intricate detail with purposeful design.",
    url: `${LIVE}/latest-news/ora-launches-the-trailer-of-a-journey-through-time`,
    image: "/images/news-trailer.jpg",
    boost: 4,
    relevance: 0.66,
    tags: ["brand", "philosophy", "design", "story", "film"],
    palette: ["#2c2620", "#57503f"],
  },
  {
    id: "leadership",
    title: "The Team",
    type: "Page",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "The executive team guiding ORA's development, hospitality and investment platforms worldwide.",
    url: `${LIVE}/about`,
    boost: 3,
    relevance: 0.6,
    tags: ["leadership", "executives", "board", "team"],
    palette: ["#2a251f", "#514a3c"],
  },
  {
    id: "sustainability",
    title: "Designing for the long term",
    type: "Page",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "ORA's approach to greenery, open space and human scale across hot climates, from 50 percent green masterplans to walkable districts.",
    url: `${LIVE}/about`,
    boost: 3,
    relevance: 0.62,
    tags: ["sustainability", "environment", "green", "climate", "esg"],
    palette: ["#8fa387", "#4c6146"],
  },

  /* News, from the live newsroom */
  {
    id: "news-maw-launch",
    title: "Iraq marks a historic milestone with the launch of Madinat Al Ward",
    titleAr: "العراق يشهد إنجازا تاريخيا بإطلاق مدينة الورد",
    type: "News",
    opco: "ORA Iraq",
    market: "Iraq",
    vertical: "Residential",
    languages: ["en", "ar"],
    date: "5 May 2025",
    snippet:
      "Baghdad's largest ever city launches: 120,000 residential units in line with Iraq's strategy to create new residential cities beyond the centre.",
    snippetAr:
      "انطلاق أكبر مدينة في تاريخ بغداد: 120 ألف وحدة سكنية ضمن استراتيجية العراق لإنشاء مدن سكنية جديدة خارج المركز.",
    url: `${LIVE}/latest-news`,
    image: "/images/news-maw.jpg",
    boost: 5,
    relevance: 0.8,
    tags: ["launch", "baghdad", "iraq", "milestone", "expansion"],
    palette: ["#d6cdbb", "#8a8276"],
    segmentBoost: { investor: 1 },
  },
  {
    id: "news-bayn-launch",
    title: "A bold new vision unveiled: ORA launches BAYN in Ghantoot",
    titleAr: "أورا تكشف عن رؤية جديدة جريئة بإطلاق بين في غنتوت",
    type: "News",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Residential",
    languages: ["en", "ar"],
    date: "24 April 2025",
    snippet:
      "The group unveils its first UAE development, a shoreline city between Dubai and Abu Dhabi.",
    snippetAr:
      "المجموعة تكشف عن أول مشاريعها الإماراتية، مدينة شاطئية بين دبي وأبوظبي.",
    url: `${LIVE}/latest-news`,
    image: "/images/news-bayn.jpg",
    boost: 6,
    relevance: 0.83,
    tags: ["launch", "uae", "dubai", "abu dhabi", "expansion", "beachfront"],
    palette: ["#dccfb8", "#94856d"],
    segmentBoost: { investor: 2 },
  },
  {
    id: "news-merveilles-open",
    title: "Merveilles Hub, Grenada's premier entertainment hub, opens its doors",
    type: "News",
    opco: "ORA Hospitality",
    market: "Grenada",
    vertical: "Hospitality",
    languages: ["en"],
    date: "18 October 2024",
    snippet:
      "Port Louis welcomes Merveilles, ORA's ode to community and discovery in the heart of the Caribbean.",
    url: `${LIVE}/latest-news`,
    image: "/images/news-merveilles.jpg",
    boost: 3,
    relevance: 0.7,
    tags: ["opening", "entertainment", "grenada", "caribbean"],
    palette: ["#cfd6cd", "#7d8a82"],
  },
  {
    id: "news-afreximbank",
    title: "ORA Developers announces a $30 million facility with Afreximbank",
    type: "News",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en"],
    date: "20 September 2024",
    snippet:
      "The group secures new financing to accelerate delivery across its African and Caribbean destinations.",
    url: `${LIVE}/latest-news`,
    image: "/images/news-afreximbank.jpg",
    boost: 3,
    relevance: 0.65,
    tags: ["financing", "afreximbank", "group", "investment"],
    palette: ["#d0cbc0", "#7f7a6e"],
    segmentBoost: { investor: 1 },
  },
  {
    id: "news-eighteen-resident",
    title: "Eighteen by ORA welcomes its first resident",
    type: "News",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Residential",
    languages: ["en"],
    date: "5 July 2023",
    snippet:
      "CEO Tarek Hamdy hands over the first villa key, marking a new era of luxury living at Eighteen.",
    url: `${LIVE}/latest-news/eighteen-by-ora-welcomes-its-first-resident`,
    image: "/images/news-eighteen-resident.jpg",
    boost: 3,
    relevance: 0.68,
    tags: ["handover", "resident", "milestone", "islamabad"],
    palette: ["#ccd1c0", "#7c8570"],
  },
  {
    id: "news-eighteen-club",
    title: "Eighteen celebrates the opening of The Club",
    type: "News",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Hospitality",
    languages: ["en"],
    date: "12 June 2023",
    snippet:
      "The championship course and clubhouse open for member play at the heart of the community.",
    url: `${LIVE}/latest-news/eighteen-celebrates-the-opening-of-the-club`,
    image: "/images/news-eighteen-club.jpg",
    boost: 3,
    relevance: 0.66,
    tags: ["golf", "opening", "club", "islamabad"],
    palette: ["#c8cdb8", "#767f66"],
  },
  {
    id: "news-yi-mykonos",
    title: "Yi Hotel Mykonos opens in Greece",
    type: "News",
    opco: "ORA Hospitality",
    market: "Greece",
    vertical: "Hospitality",
    languages: ["en"],
    date: "26 May 2023",
    snippet:
      "ORA Hospitality opens its Cycladic hideaway, bringing the group's sensorial approach to the Aegean.",
    url: `${LIVE}/latest-news/yi-hotel-mykonos-opens-in-greece`,
    image: "/images/news-yi-mykonos.jpg",
    boost: 3,
    relevance: 0.64,
    tags: ["opening", "hotel", "mykonos", "greece"],
    palette: ["#c6d0d8", "#71828f"],
  },
  {
    id: "news-trailer",
    title: "ORA launches the trailer of A Journey Through Time",
    type: "News",
    opco: "ODHL Group",
    market: "Group",
    vertical: "Corporate",
    languages: ["en"],
    date: "2 March 2023",
    snippet:
      "The group's brand film premieres, telling the story behind reimagining time across three continents.",
    url: `${LIVE}/latest-news/ora-launches-the-trailer-of-a-journey-through-time`,
    image: "/images/news-trailer.jpg",
    boost: 2,
    relevance: 0.6,
    tags: ["brand", "film", "story", "group"],
    palette: ["#cfc9bd", "#7b756a"],
  },
  {
    id: "news-anm-award",
    title: "Ayia Napa Marina receives two distinctions at the Luxury Lifestyle Awards",
    type: "News",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en"],
    date: "14 November 2022",
    snippet:
      "The Mediterranean destination takes two regional titles for design and lifestyle.",
    url: `${LIVE}/latest-news/ayia-napa-marina-receives-two-new-distinctions-at-the-luxury-lifestyle-awards-2022`,
    image: "/images/anm-events.jpg",
    boost: 3,
    relevance: 0.68,
    tags: ["award", "marina", "recognition", "mediterranean"],
    palette: ["#c9d2d6", "#76858c"],
  },

  /* Events, drafted for the POC */
  {
    id: "event-zed-park-summer",
    title: "Summer open days at ZED Park",
    titleAr: "أيام الصيف المفتوحة في حديقة زيد",
    type: "Event",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Hospitality",
    languages: ["en", "ar"],
    date: "Through August 2026",
    snippet:
      "Family weekends through August: open lawns, night markets and outdoor cinema.",
    snippetAr:
      "عطلات عائلية طوال أغسطس: مساحات مفتوحة وأسواق ليلية وسينما في الهواء الطلق.",
    url: `${LIVE}/properties/zed-elsheikh-zayed`,
    image: "/images/zed-park.jpg",
    boost: 3,
    relevance: 0.65,
    tags: ["family", "summer", "park", "cinema", "market", "children"],
    palette: ["#b6c49c", "#66754a"],
    segmentBoost: { resident: 2 },
  },
  {
    id: "event-anm-regatta",
    title: "Regatta week at Ayia Napa Marina",
    type: "Event",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en"],
    date: "September 2026",
    snippet:
      "Five days of racing, berthside dining and the season's closing concert on the waterfront stage.",
    url: `${LIVE}/properties/ayia-napa-marina`,
    image: "/images/anm-yacht-club.jpg",
    boost: 3,
    relevance: 0.63,
    tags: ["regatta", "sailing", "yachts", "concert", "summer"],
    palette: ["#9dbccb", "#4f7487"],
  },
  {
    id: "event-bayn-preview",
    title: "BAYN sales pavilion preview evenings",
    type: "Event",
    opco: "ORA UAE",
    market: "UAE",
    vertical: "Residential",
    languages: ["en"],
    date: "Weekly, by appointment",
    snippet:
      "Private previews of the Ghantoot masterplan and shorefront villa collection.",
    url: `${LIVE}/properties/bayn-by-ora`,
    image: "/images/bayn-shore.jpg",
    boost: 4,
    relevance: 0.7,
    tags: ["preview", "launch", "villas", "appointment", "uae"],
    palette: ["#d9c39a", "#9c7f4f"],
    segmentBoost: { investor: 2, firstTime: 1 },
  },
  {
    id: "event-silversands-investor",
    title: "Silversands investor evening, Dubai",
    type: "Event",
    opco: "ORA Grenada",
    market: "Grenada",
    vertical: "Corporate",
    languages: ["en"],
    date: "Quarterly",
    snippet:
      "A briefing on Caribbean returns and the citizenship route, hosted at ORA's Dubai office.",
    url: `${LIVE}/contact-us`,
    image: "/images/silversands-villas.jpg",
    boost: 3,
    relevance: 0.62,
    tags: ["investor", "citizenship", "returns", "briefing", "dubai"],
    palette: ["#b3c6ae", "#5f7a5e"],
    segmentBoost: { investor: 3 },
  },

  /* Careers, drafted for the POC */
  {
    id: "career-dev-director",
    title: "Development Director, Cairo",
    type: "Careers",
    opco: "ORA Egypt",
    market: "Egypt",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "Lead masterplan delivery across two live West Cairo districts. 15 plus years in large scale mixed use.",
    url: `${LIVE}/contact-us`,
    boost: 2,
    relevance: 0.55,
    tags: ["careers", "jobs", "development", "cairo"],
    palette: ["#c4bba9", "#6f685a"],
  },
  {
    id: "career-marina-ops",
    title: "Marina Operations Manager, Cyprus",
    type: "Careers",
    opco: "ORA Cyprus",
    market: "Cyprus",
    vertical: "Marina",
    languages: ["en"],
    snippet:
      "Run berthing, crew services and seasonal operations at a 600 vessel Mediterranean marina.",
    url: `${LIVE}/contact-us`,
    boost: 2,
    relevance: 0.54,
    tags: ["careers", "jobs", "marina", "operations", "cyprus"],
    palette: ["#b6c2c9", "#66757e"],
  },
  {
    id: "career-sales-islamabad",
    title: "Senior Sales Consultant, Islamabad",
    type: "Careers",
    opco: "ORA Pakistan",
    market: "Pakistan",
    vertical: "Corporate",
    languages: ["en"],
    snippet:
      "Guide villa and apartment buyers through Eighteen's release programme.",
    url: `${LIVE}/contact-us`,
    boost: 2,
    relevance: 0.52,
    tags: ["careers", "jobs", "sales", "islamabad"],
    palette: ["#c2bda9", "#6d6753"],
  },
];

export const itemById = new Map(items.map((i) => [i.id, i]));
